apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-db
spec:
  selector:
    matchLabels:
      app: litellm-db
  template:
    metadata:
      labels:
        app: litellm-db
    spec:
      containers:
      - name: postgres
        image: registry.redhat.io/rhel8/postgresql-13:latest
        env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: litellm-db-secret
              key: database-name
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: litellm-db-secret
              key: database-user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: litellm-db-secret
              key: database-password
        - name: PGDATA
          value: /var/lib/pgsql/data
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/pgsql/data
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 26
      securityContext:
        fsGroup: 26
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: litellm-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: litellm-db
spec:
  selector:
    app: litellm-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
