apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: litellm-proxy-scc
users:
- system:serviceaccount:litellm-dev:litellm-proxy
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1000960001
    max: 1000960001
readOnlyRootFilesystem: false
requiredDropCapabilities:
- ALL
runAsUser:
  type: MustRunAs
  uid: 1000960001
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
  ranges:
  - min: 1000960001
    max: 1000960001
volumes:
- configMap
- emptyDir
- secret
