apiVersion: v1
kind: Secret
metadata:
  name: litellm-db-secret
type: Opaque
stringData:
  username: postgres
  password: postgres
  database: litellm
  database-url: postgresql://postgres:postgres@litellm-db:5432/litellm
