name: Build and Push Image to Quay.io

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  REGISTRY: quay.io
  REPOSITORY: takinosh/litellm-proxy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Containerfile  # Specify the Containerfile instead of default Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ steps.slug.outputs.sha8 }}
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
